version: '3'
services:
  lb-node-10p:
    image: sit323-24t1-bansal-18f9eef/sit323-task10p
    ports:
      - "8037:3040"
    environment:
      - PORT=8037
    deploy:
      replicas: 3
    labels:
      - "tier=frontend"